

name: Test App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.j ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Test
      run: npm run test

  # Comment on code lines where tests fail
  # TestResultComments:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: mattallty/jest-github-action@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       test-command: "npm run test"
  #       coverage-comment: false
  #       changes-only: true

  TestCoverage:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
    - uses: actions/checkout@v2
    - uses: artiomtr/jest-coverage-report-action@v1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        threshold: 70 # optional parameter
