
name: Upload Build Artifacts

on:
  push:
    branches: [ master ]

jobs:
  CompareBundleSize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.j 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: npm ci
    - name: Webpack Stats
      run: npm run analyze
    - name: Upload Bundle Analysis Artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-bundle
        path: 'stats.js'
    